export const DISTRIBUTED_PRODUCTS = 'DISTRIBUTED_PRODUCTS'
export const WAREHOUSE_MOVEMENT = 'WAREHOUSE_MOVEMENT'

export const WAREHOUSES_STORAGE = 'WAREHOUSES_STORAGE'
export const PRODUCT_STORAGE = 'PRODUCT_STORAGE'
